### ISSUE TITLE
U8 Assembly

### ISSUE THREAD

**Issue by ferib** [cetus9/u8_r2_plugin#1]
What source did you use to map bytecode to assembly instructions?
There seems to be very little information about the whole nX-U8/100 CPU architecture.

**Comment by cetus9** [comment]
Search for FEZ0317A0-U8-INST-02 or "nX-U8/100 Core Instruction Manual"

**Comment by ferib** [comment]
@cetus9 that's funny because I searched for the exact ``nX-U8/100 Core Instruction Manual`` keywords you give me, all I seem to get are ``ML610XXXX`` manuals that make use of the nX-U8/100 CPU, in fact, they even refer to the ``nX-U8/100 Core Instruction Manual``, which might be the reason why Google keeps showing those results to me every time I search for those exact keywords.

Thanks a LOT for the ``FEZ0317A0-U8-INST-02`` keyword, this one did the trick!
